### PR TITLE
Bug/igsr 192/detect multi sample runs

### PR DESCRIPTION
**Pull request by GabeAldam**
Minor fixes to improve the detatability of unusual data loaded from the ENA.
The majority of this code is related to identifying whether an experiment is pooled. Additionally, the species data is collected and reported back to the user as this may be diagnostic of oddities in the data.

### CODE REVIEW

**Review by susanfairley — COMMENTED** [review]
I see you are testing the arg for defined - that seems right. Assuming that this has been tested pulling metadata for pooled and unrolled cases and shows the expected behaviour, I'm fine with this being merged.

**Comment by istreeter** [comment]
I don't really have an opinion, but I'm just pleased to be included in this pull request.

**Review by elowy01 — COMMENTED** [review]
Hi gab,
My Perl is a little bit rusty buy I think that the following code:
@species{$key} = ();
Should be replaced by:
$species{$key}=();

Let me know if you agree
e.

**Comment by GabeAldam** [comment]
@susanfairley thanks, I've added the test evidence to the ticket at: https://www.ebi.ac.uk/panda/jira/browse/IGSR-193

@elowy01 I don't see any usage of `@species{ ...`, only  `$species{ ...`. (I did get it wrong at one point in development but I'm fairly certain I fixed that before I raised the PR)

@istreeter I think it might be because you're watching the repo!

**Comment by elowy01** [comment]
Hi, I am happy with these changes, 
Merge it whenever you want

**Pull request merged**
